title: GameDevService
email: contact@gamedevservice.com
description: >-
  Professional Game Development Services, Blogs, and Resources
baseurl: ""
url: "https://yourcustomdomain.com"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap